services:
  postgres-its:
    image: postgres:16-alpine
    container_name: its-postgres
    environment:
      POSTGRES_USER: its_admin
      POSTGRES_PASSWORD: '#ugn#9AwxKWa*2yX@cfYt@J&'
      POSTGRES_DB: its_users_db
    ports:
      - '5433:5432'
    volumes:
      - its_postgres_data:/var/lib/postgresql/data
    networks:
      - its-network
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U its_admin -d its_users_db' ]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: its-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - its-network
    healthcheck:
      test: [ 'CMD', 'nc', '-z', 'localhost', '2181' ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: its-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - its-network
    healthcheck:
      test: [ 'CMD', 'kafka-broker-api-versions', '--bootstrap-server', 'localhost:9092' ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  its_postgres_data:
    driver: local

networks:
  its-network:
    driver: bridge
